import Config

# Production configuration for Thirdparty application
config :thirdparty, ThirdpartyWeb.Endpoint,
  # Use Bandit as the HTTP server adapter
  adapter: Bandit.PhoenixAdapter,

  # Base URL configuration for URL generation in mailers, etc.
  url: [
    host: System.fetch_env!("HOST") || "serviceexl.fairgame.club",
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],

  # Path to the static cache manifest (generated by `mix assets.deploy`)
  cache_static_manifest: "priv/static/cache_manifest.json",

  # Start the endpoint when the application starts
  server: true,

  # Disable origin checking (customize if you use CORS)
  check_origin: false,

  # Secret key base for session cookies and other secrets
  # secret_key_base: System.fetch_env!("SECRET_KEY_BASE"),

  # Disable code reloading in production
  code_reloader: false,

  # HTTP listener configuration
  http: [
    # Bind to all network interfaces
    ip: :any,
    port: String.to_integer(System.get_env("PORT") || "4000"),

    # Thousand Island (TCP) transport options
    thousand_island_options: [
      transport_options: [
        # Maximum idle time for TCP connections (in ms)
        idle_timeout: 60_000
      ]
    ],

    # Global HTTP options
    http_options: [
      # Summarize protocol errors in logs
      log_protocol_errors: :short,

      # Do not log client-initiated closures to reduce noise
      log_client_closures: false
    ],

    # HTTP/1.x specific limits and tuning
    http_1_options: [
      # Maximum length of the request line (in bytes)
      max_request_line_length:        8_192,

      # Maximum combined header length (in bytes)
      max_header_length:              8_192,

      # Maximum number of header fields
      max_header_count:               50,

      # Garbage-collect every N keep-alive requests
      gc_every_n_keepalive_requests:  5
    ]

    # For HTTP/2, WebSocket, etc., you can add:
    # http_2_options: [...],
    # websocket_options: [...]
  ]

# Configure Swoosh API Client to use Finch
config :swoosh,
  api_client: Swoosh.ApiClient.Finch,
  finch_name: Thirdparty.Finch

# Disable local memory storage for Swoosh (e.g., in favor of SMTP/other adapters)
config :swoosh, local: false

# Production logger configuration
config :logger, level: :info
